{
  "contest": 368,
  "handle": "jesjupyter",
  "risk": "2",
  "title": "`AccountingManager` can't receive ETH, thus `rescue eth` is redundant ",
  "issueId": 940,
  "issueUrl": "https://github.com/code-423n4/2024-04-noya-findings/issues/940"
}